
trigger:
  - master
pr:
  - master

pool:
  vmImage: 'macos-latest'

jobs:
  - job: 'library'
    displayName: 'Build Library'
    variables:
      MAVEN_CACHE_FOLDER: $(Agent.HomeDirectory)/.m2/repository
    steps:
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'gradlew'
        tasks: 'build'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        gradleOptions: '-Xmx1536m'
        sonarQubeRunAnalysis: false
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'gradlew'
        tasks: 'publishToMavenLocal'
        publishJUnitResults: false
        sonarQubeRunAnalysis: false
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'KermitSample/gradlew'
        workingDirectory: 'KermitSample'
        tasks: 'build'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        gradleOptions: '-Xmx3072m'
        sonarQubeRunAnalysis: false
