
trigger:
  - master
pr:
  - master

pool:
  vmImage: 'macos-latest'

stages:
  - stage: 'lib'
    displayName: 'Build Library'
    jobs:
      - job: 'build'
        displayName: 'Build and Test'
        - steps:
          - task: Gradle@2
              inputs:
                gradleWrapperFile: 'gradlew'
                tasks: 'build'
                publishJUnitResults: true
                testResultsFiles: '**/TEST-*.xml'
                javaHomeOption: 'JDKVersion'
                sonarQubeRunAnalysis: false
      - job: 'publishLocal'
        displayName: 'Publish to Maven Local'
        - steps:
            - task: Gradle@2
                inputs:
                  gradleWrapperFile: 'gradlew'
                  tasks: 'publishToMavenLocal'
  - stage: 'sample'
      displayName: 'Build Sample Project'
      jobs:
        - job: 'build'
          displayName: 'Build and Test'
            - steps:
                - task: Gradle@2
                    inputs:
                      cwd: 'KermitSample'
                      gradleWrapperFile: 'KermitSample/gradlew'
                      tasks: 'build'
                      publishJUnitResults: true
                      testResultsFiles: '**/TEST-*.xml'
                      javaHomeOption: 'JDKVersion'
                      sonarQubeRunAnalysis: false
